version: '3'

networks:
  reproxy:
    attachable: true 
    name: reproxy

secrets:
  dashboard-users:
    file: ./.secrets/dashboard-users
  regru-api-user:
    file: ./.secrets/regru-api-user
  regru-api-pwd:
    file: ./.secrets/regru-api-pwd

services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./cert:/letsencrypt
      - ./rules:/rules:ro
    environment:
      - REGRU_USERNAME_FILE=/run/secrets/regru-api-user
      - REGRU_PASSWORD_FILE=/run/secrets/regru-api-pwd
    networks:
      - reproxy
    secrets:
      - dashboard-users
      - regru-api-user
      - regru-api-pwd

