version: '3'

networks:
  reproxy:
    external: true

volumes:
  nextcloud:
  db:

secrets:
  db_root_pwd:
    file: ./.secrets/db_root_pwd
  db_pwd:
    file: ./.secrets/db_pwd
  db_user:
    file: ./.secrets/db_user
  db_name:
    file: ./.secrets/db_name
  nc_admin_user:
    file: ./.secrets/nc_admin_user
  nc_admin_pwd:
    file: ./.secrets/nc_admin_pwd
  


services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_pwd
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env
    secrets:
      - db_root_pwd
      - db_name
      - db_user
      - db_pwd
 
  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nc_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nc_admin_pwd
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.bedlamzd.dev
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=172.24.0.0/16
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    labels:
      traefik.enable: true
      traefik.docker.network: reproxy
      traefik.http.services.nc-svc.loadbalancer.server.port: 80 
    depends_on:
      - db
      - redis
    secrets:
      - nc_admin_user
      - nc_admin_pwd
      - db_name
      - db_user
      - db_pwd
    networks:
      - default
      - reproxy

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
