version: "3"

secrets:
  secret_key_file:
    file: ./jwt_secret_key

services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    depends_on:
      - back
    networks:
      - default
      - reproxy
    labels:
      traefik.enable: true
      traefik.docker.network: reproxy
      traefik.http.services.kitchenowl-front-svc.loadbalancer.server.port: 80

  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    networks:
      - default
      - reproxy
    environment:
      - JWT_SECRET_KEY="$(cat /run/secrets/secret_key_file)"
    volumes:
      - kitchenowl_data:/data
    labels:
      traefik.enable: true
      traefik.docker.network: reproxy
      traefik.http.services.kitchenowl-back-svc.loadbalancer.server.port: 80

volumes:
  kitchenowl_data:

networks:
  reproxy:
    external: true
  default:

